//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finovex
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileList
    {
        public int fileid { get; set; }
        public string filename { get; set; }
        public System.DateTime creationdDate { get; set; }
        public System.DateTime modificationDate { get; set; }
        public string filesize { get; set; }
        public string mimeType { get; set; }
        public int fileUser { get; set; }
    
        public virtual user user { get; set; }
    }
}
